
import { Prayer, Surah, Reciter } from './types';

export const PRAYERS: Prayer[] = [
  { name: 'Fajr', time: '05:12 AM' },
  { name: 'Dhuhr', time: '12:30 PM' },
  { name: 'Asr', time: '03:45 PM', isNext: true },
  { name: 'Maghrib', time: '06:15 PM' },
  { name: 'Isha', time: '07:45 PM' },
];

export const SURAHS: Surah[] = [
  { number: 1, englishName: 'Al-Fatiha', englishNameTranslation: 'The Opener', arabicName: 'الفاتحة', numberOfAyahs: 7 },
  { number: 2, englishName: 'Al-Baqarah', englishNameTranslation: 'The Cow', arabicName: 'البقرة', numberOfAyahs: 286 },
  { number: 3, englishName: 'Al-Imran', englishNameTranslation: 'Family of Imran', arabicName: 'آل عمران', numberOfAyahs: 200 },
  { number: 4, englishName: 'An-Nisa', englishNameTranslation: 'The Women', arabicName: 'النساء', numberOfAyahs: 176 },
  { number: 5, englishName: 'Al-Ma\'idah', englishNameTranslation: 'The Table Spread', arabicName: 'المائدة', numberOfAyahs: 120 },
  { number: 6, englishName: 'Al-An\'am', englishNameTranslation: 'The Cattle', arabicName: 'الأنعام', numberOfAyahs: 165 },
  { number: 7, englishName: 'Al-A\'raf', englishNameTranslation: 'The Heights', arabicName: 'الأعراف', numberOfAyahs: 206 },
  { number: 8, englishName: 'Al-Anfal', englishNameTranslation: 'The Spoils of War', arabicName: 'الأنفال', numberOfAyahs: 75 },
  { number: 18, englishName: 'Al-Kahf', englishNameTranslation: 'The Cave', arabicName: 'الكهف', numberOfAyahs: 110 },
  { number: 36, englishName: 'Ya-Sin', englishNameTranslation: 'Ya Sin', arabicName: 'يس', numberOfAyahs: 83 },
  { number: 67, englishName: 'Al-Mulk', englishNameTranslation: 'The Sovereignty', arabicName: 'الملك', numberOfAyahs: 30 },
];

export const MOCK_AYAH_ARABIC = "تَبَارَكَ الَّذِي بِيَدِهِ الْمُلْكُ وَهُوَ عَلَىٰ كُلِّ شَيْءٍ قَدِيرٌ";
export const MOCK_AYAH_TRANSLATION = "Blessed is He in whose hand is dominion, and He is over all things competent.";

export const RECITERS: Reciter[] = [
  { id: 'ar.alafasy', name: 'Mishary Rashid Alafasy', subfolder: 'Alafasy_64kbps' },
  { id: 'ar.abdulbasitmurattal', name: 'Abdul Basit \'Abd us-Samad', subfolder: 'Abdul_Basit_Murattal_64kbps' },
  { id: 'ar.abdurrahmaansudais', name: 'Abdur-Rahman as-Sudais', subfolder: 'Abdurrahmaan_As-Sudais_64kbps' },
  { id: 'ar.saoodshuraym', name: 'Sa\'ud ash-Shuraym', subfolder: 'Saood_ash-Shuraym_64kbps' },
  { id: 'ar.husary', name: 'Mahmoud Khalil Al-Hussary', subfolder: 'Husary_64kbps' },
];

export const TRANSLATIONS: Record<string, Record<string, string>> = {
  en: {
    greeting: "Assalamu Alaikum",
    upcoming: "Upcoming Prayer",
    todays_prayers: "Today's Prayers",
    schedule_header: "Prayer Schedule",
    at: "at",
    utilities: "Utilities",
    qibla: "Qibla",
    tasbih: "Tasbih",
    saved: "Saved",
    support: "Support",
    settings: "Settings",
    home: "Home",
    quran: "Quran",
    privacy: "Privacy Policy",
    terms: "Terms of Service",
    about: "About",
    location: "Location",
    auto_detect: "Auto-detect Location",
    current_city: "Current City",
    change_city: "Change City",
    cancel: "Cancel",
    calculation_header: "Prayer Calculation",
    calc_method: "Calculation Method",
    asr_method: "Asr Method (Madhab)",
    general: "General",
    recitation: "Quran Recitation",
    notifications: "Notification Sounds",
    dark_mode: "Dark Mode",
    experimental: "Experimental",
    real_compass: "Real-time Compass",
    support_dev: "Support Development",
    support_desc: "Help us keep this app free and ad-free. Your contribution is a Sadaqah Jariyah.",
    support_btn: "Support Nurly",
    privacy_assurance: "Nurly is anonymous. No accounts. No tracking. All data stays on your device.",
    search_city: "Type city name...",
    no_results: "No results found.",
    loading: "Initializing...",
    quran_reader: "The Noble Quran",
    search_quran: "Search name or number...",
    select_surah: "Select a Surah",
    select_surah_desc: "Choose a chapter from the list to begin reading.",
    tap_to_count: "Tap anywhere to count",
    reset_counter: "Reset Counter",
    restart: "Restart",
    compass_active: "Live Compass Active",
    compass_static: "Notice: Static Mode",
    grant_access: "Grant Access",
    saved_verses: "Saved Verses",
    no_saved: "No saved verses yet",
    delete: "Delete",
    go_to_verse: "Go to Verse",
    fajr_tomorrow: "Fajr (Tomorrow)",
    language: "Language",
    fajr: "Fajr",
    sunrise: "Sunrise",
    dhuhr: "Dhuhr",
    asr: "Asr",
    maghrib: "Maghrib",
    isha: "Isha",
    dhikr_complete_title: "Alhamdulillah",
    dhikr_complete_subtitle: "May Allah accept your Dhikr.",
    show_qr: "Show QR",
    hide_qr: "Hide QR",
    scan_to_send: "Scan to send",
    copied: "Copied",
    ayah: "Ayah",
    km_to_makkah: "km to Makkah",
    static_mode: "Notice: Static Mode",
    static_desc: "North is assumed to be at top. Enable sensor in Settings.",
    live_active: "LIVE COMPASS ACTIVE",
    live_desc: "Point your device towards the needle."
  },
  ar: {
    greeting: "السلام عليكم",
    upcoming: "الصلاة القادمة",
    todays_prayers: "صلوات اليوم",
    schedule_header: "مواقيت الصلاة",
    at: "الساعة",
    utilities: "أدوات",
    qibla: "القبلة",
    tasbih: "تسبيح",
    saved: "المحفوظات",
    support: "دعم",
    settings: "الإعدادات",
    home: "الرئيسية",
    quran: "القرآن",
    privacy: "Privacy Policy",
    terms: "Terms of Service",
    about: "حول التطبيق",
    location: "الموقع",
    auto_detect: "تحديد الموقع تلقائياً",
    current_city: "المدينة الحالية",
    change_city: "تغيير المدينة",
    cancel: "إلغاء",
    calculation_header: "حساب المواقيت",
    calc_method: "طريقة الحساب",
    asr_method: "مذهب العصر",
    general: "عام",
    recitation: "تلاوة القرآن",
    notifications: "أصوات التنبيه",
    dark_mode: "الوضع الداكن",
    experimental: "تجريبي",
    real_compass: "بوصلة حية",
    support_dev: "دعم التطوير",
    support_desc: "ساعدنا في الحفاظ على هذا التطبيق مجانياً وخالياً من الإعلانات.",
    support_btn: "دعم نورلي",
    privacy_assurance: "نورلي يحترم خصوصيتك. لا حسابات. لا تتبع. بياناتك تبقى على جهازك.",
    search_city: "اكتب اسم المدينة...",
    no_results: "لا توجد نتائج.",
    loading: "جاري التحميل...",
    quran_reader: "القرآن الكريم",
    search_quran: "ابحث عن سورة...",
    select_surah: "اختر سورة",
    select_surah_desc: "اختر سورة من القائمة للبدء في القراءة.",
    tap_to_count: "اضغط في أي مكان للعد",
    reset_counter: "تصفير العداد",
    restart: "إعادة",
    compass_active: "البوصلة الحية مفعلة",
    compass_static: "تنبيه: الوضع الثابت",
    grant_access: "السماح بالوصول",
    saved_verses: "الآيات المحفوظة",
    no_saved: "لا توجد آيات محفوظة",
    delete: "حذف",
    go_to_verse: "الذهاب للآية",
    fajr_tomorrow: "الفجر (غداً)",
    language: "اللغة",
    fajr: "الفجر",
    sunrise: "الشروق",
    dhuhr: "الظهر",
    asr: "العصر",
    maghrib: "المغرب",
    isha: "العشاء",
    dhikr_complete_title: "الحمد لله",
    dhikr_complete_subtitle: "تقبل الله ذكركم.",
    show_qr: "عرض QR",
    hide_qr: "إخفاء QR",
    scan_to_send: "امسح للإرسال",
    copied: "تم النسخ",
    ayah: "آية",
    km_to_makkah: "كم إلى مكة",
    static_mode: "وضع ثابت",
    static_desc: "يفترض أن الشمال في الأعلى.",
    live_active: "البوصلة الحية نشطة",
    live_desc: "وجه جهازك نحو الإبرة."
  },
  ru: {
    greeting: "Ассаляму Алейкум",
    upcoming: "Следующая молитва",
    todays_prayers: "Молитвы сегодня",
    schedule_header: "Расписание",
    at: "в",
    utilities: "Утилиты",
    qibla: "Кибла",
    tasbih: "Тасбих",
    saved: "Избранное",
    support: "Поддержать",
    settings: "Настройки",
    home: "Главная",
    quran: "Коран",
    privacy: "Privacy Policy",
    terms: "Terms of Service",
    about: "О приложении",
    location: "Местоположение",
    auto_detect: "Автоопределение",
    current_city: "Текущий город",
    change_city: "Изменить",
    cancel: "Отмена",
    calculation_header: "Расчет времени",
    calc_method: "Метод расчета",
    asr_method: "Мазхаб Асра",
    general: "Общие",
    recitation: "Чтец Корана",
    notifications: "Уведомления",
    dark_mode: "Темная тема",
    experimental: "Экспериментально",
    real_compass: "Живой компас",
    support_dev: "Поддержать проект",
    support_desc: "Помогите нам сохранить приложение бесплатным. Ваш вклад - это Садака Джария.",
    support_btn: "Поддержать Nurly",
    privacy_assurance: "Nurly анонимен. Без аккаунтов. Без слежки. Данные на вашем устройстве.",
    search_city: "Введите город...",
    no_results: "Нет результатов.",
    loading: "Загрузка...",
    quran_reader: "Священный Коран",
    search_quran: "Поиск суры...",
    select_surah: "Выберите суру",
    select_surah_desc: "Выберите главу из списка для чтения.",
    tap_to_count: "Нажмите везде для счета",
    reset_counter: "Сброс",
    restart: "Заново",
    compass_active: "Компас активен",
    compass_static: "Режим статики",
    grant_access: "Разрешить доступ",
    saved_verses: "Сохраненные аяты",
    no_saved: "Нет сохраненных аятов",
    delete: "Удалить",
    go_to_verse: "Перейти к аяту",
    fajr_tomorrow: "Фаджр (Завтра)",
    language: "Язык",
    fajr: "Фаджр",
    sunrise: "Восход",
    dhuhr: "Зухр",
    asr: "Аср",
    maghrib: "Магриб",
    isha: "Иша",
    dhikr_complete_title: "Альхамдулиллях",
    dhikr_complete_subtitle: "Да примет Аллах ваши зикры.",
    show_qr: "Показать QR",
    hide_qr: "Скрыть QR",
    scan_to_send: "Сканируйте для отправки",
    copied: "Скопировано",
    ayah: "Аят",
    km_to_makkah: "км до Мекки",
    static_mode: "Режим: Статический",
    static_desc: "Север считается сверху. Включите сенсор в настройках.",
    live_active: "ЖИВОЙ КОМПАС АКТИВЕН",
    live_desc: "Направьте устройство по стрелке."
  },
  tr: {
    greeting: "Selamun Aleyküm",
    upcoming: "Sıradaki Namaz",
    todays_prayers: "Bugünkü Namazlar",
    schedule_header: "Namaz Vakitleri",
    at: "saat",
    utilities: "Araçlar",
    qibla: "Kıble",
    tasbih: "Tesbih",
    saved: "Kaydedilenler",
    support: "Destek",
    settings: "Ayarlar",
    home: "Ana Sayfa",
    quran: "Kuran",
    privacy: "Privacy Policy",
    terms: "Terms of Service",
    about: "Hakkında",
    location: "Konum",
    auto_detect: "Otomatik Algıla",
    current_city: "Mevcut Şehir",
    change_city: "Şehir Değiştir",
    cancel: "İptal",
    calculation_header: "Vakit Hesaplama",
    calc_method: "Hesaplama Yöntemi",
    asr_method: "Asr Yöntemi (Mezhep)",
    general: "Genel",
    recitation: "Kuran Okuyucusu",
    notifications: "Bildirim Sesleri",
    dark_mode: "Karanlık Mod",
    experimental: "Deneysel",
    real_compass: "Canlı Pusula",
    support_dev: "Geliştirmeyi Destekle",
    support_desc: "Uygulamayı ücretsiz ve reklamsız tutmamıza yardım edin.",
    support_btn: "Nurly'ye Destek Ol",
    privacy_assurance: "Nurly anonimdir. Hesap yok. Takip yok. Veriler cihazınızda kalır.",
    search_city: "Şehir adı yazın...",
    no_results: "Sonuç bulunamadı.",
    loading: "Yükleniyor...",
    quran_reader: "Kuran-ı Kerim",
    search_quran: "Sure ara...",
    select_surah: "Sure Seçin",
    select_surah_desc: "Okumaya başlamak için bir sure seçin.",
    tap_to_count: "Saymak için dokunun",
    reset_counter: "Sıfırla",
    restart: "Yeniden Başlat",
    compass_active: "Pusula Aktif",
    compass_static: "Statik Mod",
    grant_access: "İzin Ver",
    saved_verses: "Kaydedilen Ayetler",
    no_saved: "Henüz kaydedilmedi",
    delete: "Sil",
    go_to_verse: "Ayete Git",
    fajr_tomorrow: "İmsak (Yarın)",
    language: "Dil",
    fajr: "İmsak",
    sunrise: "Güneş",
    dhuhr: "Öğle",
    asr: "İkindi",
    maghrib: "Akşam",
    isha: "Yatsı",
    dhikr_complete_title: "Elhamdulillah",
    dhikr_complete_subtitle: "Allah zikrini kabul etsin.",
    show_qr: "QR Göster",
    hide_qr: "QR Gizle",
    scan_to_send: "Göndermek için tara",
    copied: "Kopyalandı",
    ayah: "Ayet",
    km_to_makkah: "km Mekke'ye",
    static_mode: "Statik Mod",
    static_desc: "Kuzeyin üstte olduğu varsayılır.",
    live_active: "CANLI PUSULA AKTİF",
    live_desc: "Cihazınızı iğneye doğru tutun."
  },
  fr: {
    greeting: "Assalamu Alaikum",
    upcoming: "Prochaine Prière",
    todays_prayers: "Prières d'aujourd'hui",
    schedule_header: "Horaires",
    at: "à",
    utilities: "Utilitaires",
    qibla: "Qibla",
    tasbih: "Tasbih",
    saved: "Sauvegardé",
    support: "Soutien",
    settings: "Paramètres",
    home: "Accueil",
    quran: "Coran",
    privacy: "Privacy Policy",
    terms: "Terms of Service",
    about: "À propos",
    location: "Localisation",
    auto_detect: "Détection auto",
    current_city: "Ville actuelle",
    change_city: "Changer",
    cancel: "Annuler",
    calculation_header: "Calcul",
    calc_method: "Méthode de calcul",
    asr_method: "Méthode Asr",
    general: "Général",
    recitation: "Récitation",
    notifications: "Sons",
    dark_mode: "Mode sombre",
    experimental: "Expérimental",
    real_compass: "Boussole réelle",
    support_dev: "Soutenir le développement",
    support_desc: "Aidez-nous à garder cette application gratuite. Votre contribution est une Sadaqah Jariyah.",
    support_btn: "Soutenir Nurly",
    privacy_assurance: "Nurly est anonyme. Pas de compte. Pas de suivi.",
    search_city: "Entrez une ville...",
    no_results: "Aucun résultat.",
    loading: "Chargement...",
    quran_reader: "Le Noble Coran",
    search_quran: "Chercher sourate...",
    select_surah: "Choisir une sourate",
    select_surah_desc: "Choisissez un chapitre pour commencer.",
    tap_to_count: "Appuyez pour compter",
    reset_counter: "Réinitialiser",
    restart: "Recommencer",
    compass_active: "Boussole active",
    compass_static: "Mode statique",
    grant_access: "Autoriser",
    saved_verses: "Versets sauvegardés",
    no_saved: "Aucun verset sauvegardé",
    delete: "Supprimer",
    go_to_verse: "Aller au verset",
    fajr_tomorrow: "Fajr (Demain)",
    language: "Langue",
    fajr: "Fajr",
    sunrise: "Lever",
    dhuhr: "Dhuhr",
    asr: "Asr",
    maghrib: "Maghrib",
    isha: "Isha",
    dhikr_complete_title: "Louange à Allah",
    dhikr_complete_subtitle: "Qu'Allah accepte votre Dhikr.",
    show_qr: "Afficher QR",
    hide_qr: "Masquer QR",
    scan_to_send: "Scanner pour envoyer",
    copied: "Copié",
    ayah: "Verset",
    km_to_makkah: "km de La Mecque",
    static_mode: "Mode Statique",
    static_desc: "Le nord est supposé être en haut. Activez le capteur dans les paramètres.",
    live_active: "BOUSSOLE ACTIVE",
    live_desc: "Pointez votre appareil vers l'aiguille."
  },
  de: {
    greeting: "Assalamu Alaikum",
    upcoming: "Nächstes Gebet",
    todays_prayers: "Gebete heute",
    schedule_header: "Zeitplan",
    at: "um",
    utilities: "Dienste",
    qibla: "Qibla",
    tasbih: "Tasbih",
    saved: "Gespeichert",
    support: "Unterstützen",
    settings: "Einstellungen",
    home: "Start",
    quran: "Koran",
    privacy: "Privacy Policy",
    terms: "Terms of Service",
    about: "Über",
    location: "Standort",
    auto_detect: "Auto-Erkennung",
    current_city: "Aktuelle Stadt",
    change_city: "Ändern",
    cancel: "Abbrechen",
    calculation_header: "Berechnung",
    calc_method: "Rechenmethode",
    asr_method: "Asr Methode",
    general: "Allgemein",
    recitation: "Rezitation",
    notifications: "Töne",
    dark_mode: "Dunkelmodus",
    experimental: "Experimentell",
    real_compass: "Live-Kompass",
    support_dev: "Entwicklung unterstützen",
    support_desc: "Helfen Sie uns, diese App kostenlos zu halten.",
    support_btn: "Nurly unterstützen",
    privacy_assurance: "Nurly ist anonym. Keine Konten. Kein Tracking.",
    search_city: "Stadt eingeben...",
    no_results: "Keine Ergebnisse.",
    loading: "Laden...",
    quran_reader: "Der Edle Koran",
    search_quran: "Suche...",
    select_surah: "Sure auswählen",
    select_surah_desc: "Wählen Sie ein Kapitel zum Lesen.",
    tap_to_count: "Tippen zum Zählen",
    reset_counter: "Zurücksetzen",
    restart: "Neustart",
    compass_active: "Kompass aktiv",
    compass_static: "Statischer Modus",
    grant_access: "Erlauben",
    saved_verses: "Gespeicherte Verse",
    no_saved: "Keine Verse",
    delete: "Löschen",
    go_to_verse: "Zum Vers",
    fajr_tomorrow: "Fajr (Morgen)",
    language: "Sprache",
    fajr: "Fajr",
    sunrise: "Sonnenaufgang",
    dhuhr: "Dhuhr",
    asr: "Asr",
    maghrib: "Maghrib",
    isha: "Isha",
    dhikr_complete_title: "Gepriesen sei Allah",
    dhikr_complete_subtitle: "Möge Allah Ihr Dhikr annehmen.",
    show_qr: "QR anzeigen",
    hide_qr: "QR verbergen",
    scan_to_send: "Scannen zum Senden",
    copied: "Kopiert",
    ayah: "Vers",
    km_to_makkah: "km nach Mekka",
    static_mode: "Statischer Modus",
    static_desc: "Norden ist oben. Sensor in Einstellungen aktivieren.",
    live_active: "KOMPASS AKTIV",
    live_desc: "Richten Sie Ihr Gerät auf die Nadel."
  },
  es: {
    greeting: "Assalamu Alaikum",
    upcoming: "Próxima Oración",
    todays_prayers: "Oraciones de hoy",
    schedule_header: "Horario",
    at: "a las",
    utilities: "Utilidades",
    qibla: "Qibla",
    tasbih: "Tasbih",
    saved: "Guardado",
    support: "Apoyo",
    settings: "Ajustes",
    home: "Inicio",
    quran: "Corán",
    privacy: "Privacy Policy",
    terms: "Terms of Service",
    about: "Acerca de",
    location: "Ubicación",
    auto_detect: "Auto-detectar",
    current_city: "Ciudad actual",
    change_city: "Cambiar",
    cancel: "Cancelar",
    calculation_header: "Cálculo",
    calc_method: "Método de cálculo",
    asr_method: "Método Asr",
    general: "General",
    recitation: "Recitación",
    notifications: "Sonidos",
    dark_mode: "Modo oscuro",
    experimental: "Experimental",
    real_compass: "Brújula en vivo",
    support_dev: "Apoyar desarrollo",
    support_desc: "Ayúdanos a mantener esta aplicación gratuita.",
    support_btn: "Apoyar a Nurly",
    privacy_assurance: "Nurly es anónimo. Sin cuentas. Sin rastreo.",
    search_city: "Escriba ciudad...",
    no_results: "Sin resultados.",
    loading: "Cargando...",
    quran_reader: "El Noble Corán",
    search_quran: "Buscar...",
    select_surah: "Seleccionar Sura",
    select_surah_desc: "Elige un capítulo para leer.",
    tap_to_count: "Toque para contar",
    reset_counter: "Reiniciar",
    restart: "Reiniciar",
    compass_active: "Brújula activa",
    compass_static: "Modo estático",
    grant_access: "Permitir",
    saved_verses: "Versos guardados",
    no_saved: "Sin versos guardados",
    delete: "Borrar",
    go_to_verse: "Ir al verso",
    fajr_tomorrow: "Fajr (Mañana)",
    language: "Idioma",
    fajr: "Fajr",
    sunrise: "Amanecer",
    dhuhr: "Dhuhr",
    asr: "Asr",
    maghrib: "Maghrib",
    isha: "Isha",
    dhikr_complete_title: "Alabado sea Allah",
    dhikr_complete_subtitle: "Que Allah acepte tu Dhikr.",
    show_qr: "Mostrar QR",
    hide_qr: "Ocultar QR",
    scan_to_send: "Escanear para enviar",
    copied: "¡Copiado!",
    ayah: "Aleya",
    km_to_makkah: "km a La Meca",
    static_mode: "Modo Estático",
    static_desc: "Se asume norte arriba. Active sensor en Ajustes.",
    live_active: "BRÚJULA ACTIVA",
    live_desc: "Apunte su dispositivo hacia la aguja."
  }
};
